### ISSUE TITLE
Doesn't import correctly

### ISSUE THREAD

**Issue by dlnsk** [ooyun0/siiimple-toast#13]
When I import library like`import toast from 'siiimple-toast';`
`toast` equals empty object.

**Comment by ooyun0** [comment]
Thanks for the report @dlnsk!
I re-bundled and updated the pacakge.
If you update to v3.1.7, it should work fine.

**Comment by dlnsk** [comment]
Webpack says:

> WARNING in ./node_modules/siiimple-toast/dist/main.js 1:292-296
> Critical dependency: the request of a dependency is an expression

webpack@4.39.3

**Comment by ooyun0** [comment]
It's parcel's [issue](parcel-bundler/parcel#2883), will be fixed in [v2](parcel-bundler/parcel#3129).
I'll let you know when this problem is solved.

**Comment by dlnsk** [comment]
Still here...
